//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCatalogue
    {
        public TemplateCatalogue()
        {
            this.Metadatas = new HashSet<Metadata>();
        }
    
        public int TemplateId { get; set; }
        public int VersionNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Comments { get; set; }
        public string TemplateBody { get; set; }
    
        public virtual ICollection<Metadata> Metadatas { get; set; }
    }
}
